[package]
name = "ligmir"
version = "0.1.0"
authors = ["Ruslan Fadeev <kinrany@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.8"
headless_chrome = { version = "0.9.0", default-features = false }
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "9671115796e42865eaebd020ac27542802027b02" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev = "9671115796e42865eaebd020ac27542802027b02" }
teloxide = { version = "0.3.3", default-features = false }
